resolver: lts-9.0
#resolver: nightly-2017-08-15

packages:
- .

extra-deps: [ spatial-math-0.4.0.0
            ]

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

