resolver: lts-9.0

packages:
- .

extra-deps: [ generic-accessors-0.6.0.1
            , spatial-math-0.4.0.0
            ]

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

